"use strict";
const md = new MusicDisplay("canvas1");
const s = md.makeStaff("treble", 100, 100, 1200, "both");
s.addKeySignature(["B4b", "E5b"]);
s.addTimeSignature("3", "4");
s.addNote("", "A3", "whole");
s.addNote("sharp", "C4", "quarter");
s.addNote("sharp", "D4", "half");
s.addRest("quarter");
s.addBarLine();
s.addNote("", "F4", "whole");
s.addNote("sharp", "C4", "whole");
s.addBarLine();
s.addNote("", "G4", "quarter");
s.addNote("flat", "A4", "half");
s.addBarLine();
s.addNote("", "D5", "whole");
s.addRest("whole");
s.addBarLine();
s.addNote("sharp", "F5", "whole");
s.addNote("", "G5", "half");
s.addRest("half");
s.addNote("", "A5", "quarter");
s.addNote("", "C6", "whole");
s.addNote("flat", "D6", "whole");
s.draw();
s.showAll("showAll1");
s.hideAll("hideAll1");

const md2 = new MusicDisplay("canvas2");
const s2 = md2.makeStaff("bass", 0, 100, 800, "hover");
s2.addKeySignature(["C3#", "F3#"]);
s2.addTimeSignature("4", "4");
s2.addNote("", "F2", "whole");
s2.addNote("", "G2", "quarter");
s2.addNote("", "A2", "whole");
s2.addNote("", "B2", "half");
s2.addNote("", "C3", "whole");
s2.addNote("", "D3", "quarter");
s2.addNote("", "E3", "whole");
s2.addNote("", "F3", "whole");
s2.addNote("", "G3", "quarter");
s2.addNote("", "A3", "whole");
s2.addNote("", "B3", "whole");
s2.draw();
s2.showAll("showAll2");
s2.hideAll("hideAll2");

const md3 = new MusicDisplay("canvas3");
const s3 = md3.makeStaff("treble", 400, 100, 500, "click");
s3.addTimeSignature("2", "4");
s3.addNote("flat", "B4", "whole");
s3.addNote("flat", "E5", "quarter");
s3.addNote("", "G4", "whole");
s3.addNote("flat", "A4", "quarter");
s3.addNote("", "C5", "whole");
s3.draw();
