"use strict";
const md = new MusicDisplay();
const s = md.makeStaff("treble", 100, 100, 1200, true);
s.draw();
s.addKeySignature(["B4b", "E5b"]);
s.addTimeSignature("3", "4");
s.addNote("", "A3", "whole");
s.addNote("sharp", "C4", "whole");
s.addNote("sharp", "D4", "whole");
s.addRest("quarter");
s.addBarLine();
s.addNote("", "F4", "whole");
s.addNote("sharp", "C4", "whole");
s.addBarLine();
s.addNote("", "G4", "whole");
s.addNote("flat", "A4", "whole");
s.addBarLine();
s.addNote("", "D5", "whole");
s.addRest("whole");
s.addBarLine();
s.addNote("sharp", "F5", "whole");
s.addNote("", "G5", "whole");
s.addRest("half");
s.addNote("", "A5", "whole");
s.addNote("", "C6", "whole");
s.addNote("flat", "D6", "whole");

const s2 = md.makeStaff("bass", 300, 400, 800, true);
s2.draw();
s2.addKeySignature(["C3#", "F3#"]);
s2.addTimeSignature("4", "4");
s2.addNote("", "F2", "whole");
s2.addNote("", "G2", "whole");
s2.addNote("", "A2", "whole");
s2.addNote("", "B2", "whole");
s2.addNote("", "C3", "whole");
s2.addNote("", "D3", "whole");
s2.addNote("", "E3", "whole");
s2.addNote("", "F3", "whole");
s2.addNote("", "G3", "whole");
s2.addNote("", "A3", "whole");
s2.addNote("", "B3", "whole");

const s3 = md.makeStaff("treble", 100, 700, 500, false);
s3.draw();
s3.addTimeSignature("2", "4");
s3.addNote("flat", "B4", "whole");
s3.addNote("flat", "E5", "whole");
s3.addNote("", "G4", "whole");
s3.addNote("flat", "A4", "whole");
s3.addNote("", "C5", "whole");